# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b205e4cdf7a739326ba88d2a75c55297c97b961e165c0c302eecd01a4259cb4da2f9561dee4ff7c6aa65bfea4f0d3882cecfdd79389104678688ef076312a36

test:
  secret_key_base: 78f4e9fb48fac05d25154b990bde11100510daf6490000f73f238c46f145e253b82cfd6c74e4475b61ec46ef3177e13407ecd6a5ed92e50482b66e84026aae5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
